from __future__ import annotations

import hashlib
import json
import random
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

COMMENT_RE = re.compile(r"//|/\*|\*/")
GENERATED_RE = re.compile(r"Code generated|DO NOT EDIT|generated by", re.IGNORECASE)
TEST_PATH_RE = re.compile(r"(^|/)(testdata|vendor|mock|mocks|fixture|fixtures|example|examples|generated)(/|$)", re.IGNORECASE)
TEST_SYMBOL_RE = re.compile(r"\b(Test|Benchmark|Example|assert|require|testcase|expected|actual)\b", re.IGNORECASE)
TEST_IMPORT_RE = re.compile(r'\bimport\s*(?:\([^)]*(?:"testing"|"github\.com/stretchr/testify/(?:assert|require)")[^)]*\)|"testing"|"github\.com/stretchr/testify/(?:assert|require)")', re.DOTALL)
NOISY_CALL_RE = re.compile(r"\b(?:fmt|log)\.Print(?:f|ln)?\b|\bpanic\s*\(|\bos\.Exit\s*\(")
FUNC_RE_TEMPLATE = r"\bfunc\s+(?:\([^)]*\)\s*)?{name}\s*\("
ASSIGN_OP_RE = re.compile(r"(?<![=!<>:])(?::=|=|\+=|-=|\*=|/=|%=|&=|\|=|\^=|<<=|>>=)(?![=>])")
CALL_RE = re.compile(r"^(?:[A-Za-z_]\w*|[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)+)\s*\(.*\)$")
LOW_INFO_RETURNS = {
    "return nil",
    "return err",
    "return nil, err",
    "return false",
    "return true",
    "return 0",
    "return \"\"",
}
BLOCK_KEYWORDS = (
    "if ", "for ", "switch ", "select ", "case ", "default:", "else",
    "defer ", "go ", "var ", "const ", "type ", "func ", "range ",
)
CONTROL_LOW_INFO = {"continue", "break", "fallthrough"}

TARGET_RATIOS = {"assignment": 0.45, "return": 0.30, "call": 0.25}


@dataclass(frozen=True)
class CandidateSpan:
    start: int
    end: int
    target: str
    target_kind: str
    line_no: int


@dataclass
class BuildStats:
    files_seen: int = 0
    rows_seen: int = 0
    rows_accepted: int = 0
    candidates_seen: int = 0
    reject_reasons: Counter[str] = None  # type: ignore[assignment]
    target_kinds: Counter[str] = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.reject_reasons is None:
            self.reject_reasons = Counter()
        if self.target_kinds is None:
            self.target_kinds = Counter()

    def reject(self, reason: str) -> None:
        self.reject_reasons[reason] += 1

    def accept(self, kind: str) -> None:
        self.rows_accepted += 1
        self.target_kinds[kind] += 1


def iter_jsonl(path: Path) -> Iterable[dict[str, Any]]:
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    with path.open("w", encoding="utf-8") as f:
        for obj in rows:
            f.write(json.dumps(obj, ensure_ascii=False) + "\n")
            n += 1
    return n


def normalize_code(code: str) -> str:
    code = re.sub(r'"(?:[^"\\]|\\.)*"', '"STR"', code)
    code = re.sub(r"'[^'\\]*(?:\\.[^'\\]*)*'", "'STR'", code)
    code = re.sub(r"\b\d+(?:\.\d+)?\b", "NUM", code)
    code = re.sub(r"\s+", "", code)
    return code


def count_nonempty_lines(code: str) -> int:
    return sum(1 for line in code.splitlines() if line.strip())


def stable_hash(text: str, n: int = 16) -> str:
    return hashlib.sha1(text.encode("utf-8", errors="ignore")).hexdigest()[:n]


def has_comment(text: str) -> bool:
    return bool(COMMENT_RE.search(text))


def has_balanced_braces_without_comments_or_strings(code: str, open_pos: int) -> int:
    depth = 0
    i = open_pos
    in_string: str | None = None
    escaped = False
    while i < len(code):
        ch = code[i]
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == in_string:
                in_string = None
            i += 1
            continue
        if ch in {'"', "'", '`'}:
            in_string = ch
            i += 1
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return -1


def find_function_slice(code: str, func_name: str | None = None) -> tuple[int, int, str] | None:
    if func_name:
        pat = re.compile(FUNC_RE_TEMPLATE.format(name=re.escape(func_name)))
        m = pat.search(code)
    else:
        m = re.search(r"\bfunc\s+(?:\([^)]*\)\s*)?[A-Za-z_]\w*\s*\(", code)
    if not m:
        return None
    brace = code.find("{", m.end())
    if brace < 0:
        return None
    end = has_balanced_braces_without_comments_or_strings(code, brace)
    if end < 0:
        return None
    return m.start(), end + 1, code[m.start():end + 1]


def function_body_bounds(function_code: str) -> tuple[int, int] | None:
    brace = function_code.find("{")
    if brace < 0:
        return None
    end = has_balanced_braces_without_comments_or_strings(function_code, brace)
    if end < 0:
        return None
    return brace + 1, end


def classify_target(line: str) -> str | None:
    stripped = line.strip()
    if not stripped:
        return None
    if stripped.endswith(";"):
        stripped = stripped[:-1].rstrip()
    if not stripped or "{" in stripped or "}" in stripped or ";" in stripped:
        return None
    if has_comment(stripped) or NOISY_CALL_RE.search(stripped) or TEST_SYMBOL_RE.search(stripped):
        return None
    lowered = stripped.lower()
    if lowered in CONTROL_LOW_INFO:
        return None
    if lowered.startswith(BLOCK_KEYWORDS):
        return None
    if lowered.startswith("return"):
        if not re.match(r"^return\s+\S", stripped):
            return None
        if lowered in LOW_INFO_RETURNS:
            return None
        return "return"
    if ASSIGN_OP_RE.search(stripped):
        if "==" in stripped or "!=" in stripped or "<=" in stripped or ">=" in stripped:
            # Keep assignment ops but reject likely conditions with comparisons.
            if ":=" not in stripped and not re.search(r"[+\-*/%&|^<>]?=", stripped):
                return None
        lhs = re.split(r":=|\+=|-=|\*=|/=|%=|&=|\|=|\^=|<<=|>>=|=", stripped, maxsplit=1)[0].strip()
        if not lhs or lhs == "_":
            return None
        return "assignment"
    if CALL_RE.match(stripped):
        callee = stripped.split("(", 1)[0].strip()
        if callee in {"panic", "println", "print"}:
            return None
        return "call"
    return None


def extract_statement_candidates(function_code: str) -> tuple[list[CandidateSpan], str | None]:
    if has_comment(function_code):
        return [], "function_has_comment"
    if GENERATED_RE.search(function_code):
        return [], "generated_code"
    if TEST_SYMBOL_RE.search(function_code):
        return [], "test_symbol_in_function"
    if NOISY_CALL_RE.search(function_code):
        return [], "noisy_call_in_function"
    bounds = function_body_bounds(function_code)
    if bounds is None:
        return [], "no_function_body"
    body_start, body_end = bounds
    body = function_code[body_start:body_end]
    line_count = len([ln for ln in body.splitlines() if ln.strip()])
    if line_count < 2:
        return [], "function_too_short"
    if line_count > 80:
        return [], "function_too_long"

    candidates: list[CandidateSpan] = []
    offset = 0
    for line_no, raw_line in enumerate(function_code.splitlines(keepends=True), start=1):
        line_start = offset
        line_end = offset + len(raw_line)
        offset = line_end
        if line_end <= body_start or line_start >= body_end:
            continue
        text_no_nl = raw_line[:-1] if raw_line.endswith("\n") else raw_line
        stmt_end = line_start + len(text_no_nl)
        kind = classify_target(text_no_nl)
        if not kind:
            continue
        stripped_tokens = re.findall(r"[A-Za-z_]\w*|\S", text_no_nl.strip())
        if len(stripped_tokens) < 3 or len(stripped_tokens) > 40:
            continue
        candidates.append(CandidateSpan(
            start=line_start,
            end=stmt_end,
            target=text_no_nl,
            target_kind=kind,
            line_no=line_no,
        ))
    return candidates, None


def should_reject_codesearchnet_row(row: dict[str, Any]) -> str | None:
    path = str(row.get("path") or "")
    code = str(row.get("code") or row.get("original_string") or "")
    func_name = str(row.get("func_name") or "")
    if path.endswith("_test.go"):
        return "test_file"
    if TEST_PATH_RE.search(path):
        return "test_path"
    if GENERATED_RE.search(code):
        return "generated_code"
    if TEST_IMPORT_RE.search(code):
        return "test_import"
    if TEST_SYMBOL_RE.search(func_name) or TEST_SYMBOL_RE.search(code):
        return "test_symbol"
    if has_comment(code):
        return "code_has_comment"
    if NOISY_CALL_RE.search(code):
        return "noisy_call"
    return None


def make_canonical_sample(
    *,
    uid: str,
    source_dataset: str,
    split: str,
    function_code: str,
    cand: CandidateSpan,
    metadata: dict[str, Any],
    judge_payload: dict[str, Any] | None = None,
) -> dict[str, Any]:
    prefix = function_code[:cand.start]
    target = cand.target
    suffix = function_code[cand.end:]
    full_code = prefix + target + suffix
    return {
        "uid": uid,
        "source_dataset": source_dataset,
        "split": split,
        "language": "go",
        "task_type": "go_single_statement_completion",
        "prefix": prefix,
        "target": target,
        "suffix": suffix,
        "full_code": full_code,
        "target_kind": cand.target_kind,
        "metadata": metadata,
        "judge_payload": judge_payload or {"kind": "none"},
    }


def render_chatml(sample: dict[str, Any]) -> dict[str, Any]:
    user = (
        "Fill the [MASK] in the Go function. Return only the missing Go code, "
        "without Markdown fences or explanation.\n\n"
        "* Incomplete Code:\n"
        f"{sample['prefix']}[MASK]{sample['suffix']}"
    )
    out = dict(sample)
    out["messages"] = [
        {"role": "system", "content": "You are a Go code completion assistant."},
        {"role": "user", "content": user},
        {"role": "assistant", "content": sample["target"]},
    ]
    out["only_last_turn_loss"] = True
    return out


def build_codesearchnet_candidates(
    paths: list[Path],
    *,
    max_rows: int | None = None,
    stats: BuildStats | None = None,
) -> list[dict[str, Any]]:
    stats = stats or BuildStats()
    samples: list[dict[str, Any]] = []
    seen_norm: set[str] = set()
    for path in paths:
        stats.files_seen += 1
        for row in iter_jsonl(path):
            if max_rows is not None and stats.rows_seen >= max_rows:
                return samples
            stats.rows_seen += 1
            reason = should_reject_codesearchnet_row(row)
            if reason:
                stats.reject(reason)
                continue
            code = str(row.get("code") or row.get("original_string") or "")
            func_slice = find_function_slice(code, row.get("func_name")) or (0, len(code), code)
            _, _, function_code = func_slice
            cands, reason = extract_statement_candidates(function_code)
            if reason:
                stats.reject(reason)
                continue
            for j, cand in enumerate(cands):
                stats.candidates_seen += 1
                norm_key = stable_hash(normalize_code(function_code) + "\n" + normalize_code(cand.target))
                if norm_key in seen_norm:
                    stats.reject("duplicate_normalized")
                    continue
                seen_norm.add(norm_key)
                uid = f"codesearchnet_go_train_{stable_hash(str(row.get('repo', '')) + str(row.get('path', '')) + str(row.get('func_name', '')) + str(cand.line_no) + cand.target)}"
                sample = make_canonical_sample(
                    uid=uid,
                    source_dataset="codesearchnet_go",
                    split="train",
                    function_code=function_code,
                    cand=cand,
                    metadata={
                        "repo": row.get("repo"),
                        "source_path": row.get("path"),
                        "function_name": row.get("func_name"),
                        "sha": row.get("sha"),
                        "url": row.get("url"),
                        "target_line": cand.line_no,
                        "target_span": [cand.start, cand.end],
                        "function_line_count": count_nonempty_lines(function_code),
                        "filters": ["no_comments", "single_line", cand.target_kind],
                    },
                )
                samples.append(sample)
                stats.accept(cand.target_kind)
    return samples


def _mceval_files(root: Path) -> list[Path]:
    return sorted(root.rglob("Go.jsonl"))


def join_mceval_prompt_solution(prompt: str, solution: str) -> str:
    if prompt and solution and not prompt.endswith(("\n", "\r")) and not solution.startswith(("\n", "\r")):
        return prompt + "\n" + solution
    return prompt + solution


def build_mceval_candidates(
    root: Path,
    *,
    per_task: int = 3,
    stats: BuildStats | None = None,
) -> list[dict[str, Any]]:
    stats = stats or BuildStats()
    samples: list[dict[str, Any]] = []
    seen_task_solution: set[str] = set()
    seen_uid: set[str] = set()
    for path in _mceval_files(root):
        stats.files_seen += 1
        for row in iter_jsonl(path):
            stats.rows_seen += 1
            prompt = str(row.get("prompt") or "")
            solution = str(row.get("canonical_solution") or "")
            entry = str(row.get("entry_point") or "")
            if not prompt or not solution or not entry:
                stats.reject("missing_mceval_fields")
                continue
            task_key = stable_hash(entry + "\n" + solution)
            if task_key in seen_task_solution:
                stats.reject("duplicate_mceval_task")
                continue
            seen_task_solution.add(task_key)
            full_code = join_mceval_prompt_solution(prompt, solution)
            func_slice = find_function_slice(full_code, entry)
            if func_slice is None:
                stats.reject("entry_function_not_found")
                continue
            func_start, func_end, function_code = func_slice
            trailing_code = full_code[func_end:]
            cands, reason = extract_statement_candidates(function_code)
            if reason:
                stats.reject(reason)
                continue
            kept = 0
            for cand in cands:
                if kept >= per_task:
                    break
                stats.candidates_seen += 1
                full_target_start = func_start + cand.start
                full_target_end = func_start + cand.end
                uid = f"mceval_go_{stable_hash(str(row.get('task_id', '')) + entry + str(cand.line_no) + cand.target)}"
                if uid in seen_uid:
                    stats.reject("duplicate_uid")
                    continue
                seen_uid.add(uid)
                sample = make_canonical_sample(
                    uid=uid,
                    source_dataset="mceval_go",
                    split="eval",
                    function_code=function_code,
                    cand=cand,
                    metadata={
                        "task_id": row.get("task_id"),
                        "entry_point": entry,
                        "signature": row.get("signature"),
                        "source_file": str(path),
                        "target_line": cand.line_no,
                        "target_span": [cand.start, cand.end],
                        "full_file_target_span": [full_target_start, full_target_end],
                        "function_line_count": count_nonempty_lines(function_code),
                        "filters": ["no_comments", "single_line", cand.target_kind],
                    },
                    judge_payload={
                        "kind": "mceval_go_test",
                        "task_id": row.get("task_id"),
                        "test": row.get("test"),
                        "entry_point": entry,
                        "judge_prefix": function_code[:cand.start],
                        "judge_suffix": function_code[cand.end:] + trailing_code,
                        "full_prefix": full_code[:full_target_start],
                        "full_suffix": full_code[full_target_end:],
                        "raw_mceval": row,
                    },
                )
                samples.append(sample)
                stats.accept(cand.target_kind)
                kept += 1
    return samples


def select_train_subset(samples: list[dict[str, Any]], n: int, seed: int) -> list[dict[str, Any]]:
    if n <= 0 or len(samples) <= n:
        return list(samples)
    rng = random.Random(seed)
    by_kind: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for sample in samples:
        by_kind[sample.get("target_kind", "unknown")].append(sample)
    selected: list[dict[str, Any]] = []
    used: set[str] = set()
    for kind, ratio in TARGET_RATIOS.items():
        quota = int(round(n * ratio))
        bucket = by_kind.get(kind, [])
        rng.shuffle(bucket)
        for sample in bucket[:quota]:
            selected.append(sample)
            used.add(sample["uid"])
    if len(selected) < n:
        rest = [s for s in samples if s["uid"] not in used]
        rng.shuffle(rest)
        selected.extend(rest[: n - len(selected)])
    rng.shuffle(selected)
    return selected[:n]




def _line_counts(samples: list[dict[str, Any]]) -> list[int]:
    vals: list[int] = []
    for sample in samples:
        value = sample.get("metadata", {}).get("function_line_count")
        if isinstance(value, int):
            vals.append(value)
    return vals


def line_count_summary(samples: list[dict[str, Any]]) -> dict[str, Any]:
    vals = sorted(_line_counts(samples))
    if not vals:
        return {"n": 0}
    def pct(q: float) -> int:
        idx = min(len(vals) - 1, max(0, round((len(vals) - 1) * q)))
        return vals[idx]
    return {
        "n": len(vals),
        "min": vals[0],
        "p25": pct(0.25),
        "median": pct(0.50),
        "p75": pct(0.75),
        "p90": pct(0.90),
        "max": vals[-1],
    }


def filter_by_function_lines(
    samples: list[dict[str, Any]],
    *,
    max_lines: int | None = None,
    quantile: float = 1.0,
) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    before = len(samples)
    out = list(samples)
    threshold: int | None = max_lines if max_lines and max_lines > 0 else None
    if 0 < quantile < 1 and out:
        vals = sorted(_line_counts(out))
        if vals:
            idx = min(len(vals) - 1, max(0, round((len(vals) - 1) * quantile)))
            q_threshold = vals[idx]
            threshold = q_threshold if threshold is None else min(threshold, q_threshold)
    if threshold is not None:
        out = [s for s in out if int(s.get("metadata", {}).get("function_line_count", 10**9)) <= threshold]
    info = {
        "before": before,
        "after": len(out),
        "threshold": threshold,
        "quantile": quantile,
        "max_lines": max_lines,
    }
    return out, info

def write_report(
    path: Path,
    *,
    title: str,
    train_stats: BuildStats,
    eval_stats: BuildStats,
    train_samples: list[dict[str, Any]],
    eval_samples: list[dict[str, Any]],
    train_line_filter: dict[str, Any] | None = None,
    eval_line_filter: dict[str, Any] | None = None,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append(f"# {title}")
    lines.append("")
    for name, stats, samples, line_filter in [
        ("Train / CodeSearchNet", train_stats, train_samples, train_line_filter),
        ("Eval / MCEval", eval_stats, eval_samples, eval_line_filter),
    ]:
        lines.append(f"## {name}")
        lines.append("")
        lines.append(f"- files_seen: {stats.files_seen}")
        lines.append(f"- rows_seen: {stats.rows_seen}")
        lines.append(f"- candidates_seen: {stats.candidates_seen}")
        lines.append(f"- final_samples: {len(samples)}")
        if line_filter:
            lines.append(f"- line_filter: {line_filter}")
        lines.append(f"- function_line_count: {line_count_summary(samples)}")
        lines.append("")
        lines.append("### target_kind")
        lines.append("")
        for kind, count in Counter(s.get("target_kind", "unknown") for s in samples).most_common():
            lines.append(f"- {kind}: {count}")
        lines.append("")
        lines.append("### reject_reasons")
        lines.append("")
        for reason, count in stats.reject_reasons.most_common(30):
            lines.append(f"- {reason}: {count}")
        lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_samples_report(path: Path, samples: list[dict[str, Any]], *, limit: int = 50, seed: int = 42) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rng = random.Random(seed)
    rows = list(samples)
    rng.shuffle(rows)
    rows = rows[:limit]
    lines = ["# GoSingle Sample Preview", ""]
    for i, sample in enumerate(rows, start=1):
        lines.append(f"## {i}. {sample['uid']} ({sample.get('target_kind')})")
        lines.append("")
        lines.append(f"source_dataset: `{sample.get('source_dataset')}`")
        lines.append("")
        lines.append("```go")
        lines.append(sample["prefix"] + "[MASK]" + sample["suffix"])
        lines.append("```")
        lines.append("")
        lines.append("target:")
        lines.append("")
        lines.append("```go")
        lines.append(sample["target"])
        lines.append("```")
        lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
